version: '3.7'

services:
  #
  # build
  #
  taiga-build-frontend:
    build:
      context: .
      target: build
    image: takumi/taiga-frontend:build
    hostname: taiga-build-frontend
    container_name: taiga-build-frontend
    networks:
      - taiga

  #
  # service
  #
  taiga-test-frontend:
    build:
      context: .
      target: prod
    image: takumi/taiga-frontend:latest
    hostname: taiga-test-frontend
    container_name: taiga-test-frontend
    # cap_add:
    #   - CHOWN
    #   - SETUID
    #   - SETGID
    #   - FOWNER
    # cap_drop:
    #   - ALL
    networks:
      - taiga
    ports:
      - 8000:80
    depends_on:
      - taiga-test-events
      - taiga-test-backend
    volumes:
      - type: volume
        source: taiga-test-backend-media
        target: /taiga-frontend/media
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: taiga-test-backend-static
        target: /taiga-frontend/static
        read_only: true
        volume:
          nocopy: true
    env_file:
      - ./test.env

  #
  # events
  #
  taiga-test-events:
    image: takumi/taiga-events:latest
    hostname: taiga-test-events
    container_name: taiga-test-events
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-test-rabbitmq
    env_file:
      - ./test.env

  #
  # backend
  #
  taiga-test-backend:
    image: takumi/taiga-backend:alpine
    hostname: taiga-test-backend
    container_name: taiga-test-backend
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-test-postgres
      - taiga-test-memcached
      - taiga-test-rabbitmq
      - taiga-test-redis
    volumes:
      - taiga-test-backend-media:/taiga-backend/media
      - taiga-test-backend-static:/taiga-backend/static
    env_file:
      - ./test.env

  #
  # postgres
  #
  taiga-test-postgres:
    image: postgres:9-alpine
    hostname: taiga-test-postgres
    container_name: taiga-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C

  #
  # memcached
  #
  taiga-test-memcached:
    image: memcached:alpine
    hostname: taiga-test-memcached
    container_name: taiga-test-memcached
    cap_drop:
      - ALL
    networks:
      - taiga
    env_file:
      - ./test.env

  #
  # rabbitmq
  #
  taiga-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-test-rabbitmq
    container_name: taiga-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      - RABBITMQ_DEFAULT_USER=taiga
      - RABBITMQ_DEFAULT_PASS=taiga
      - RABBITMQ_DEFAULT_VHOST=taiga

  #
  # redis
  #
  taiga-test-redis:
    image: redis:alpine
    hostname: taiga-test-redis
    container_name: taiga-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
volumes:
  taiga-test-backend-media:
  taiga-test-backend-static:
