version: '3.7'

services:
  #
  # build
  #
  taiga-frontend-build:
    build:
      context: .
      target: build
    image: takumi/taiga-frontend:build
    hostname: taiga-frontend-build
    container_name: taiga-frontend-build
    networks:
      - taiga

  #
  # service
  #
  taiga-frontend-test:
    build:
      context: .
      target: prod
    image: takumi/taiga-frontend:latest
    hostname: taiga-frontend-test
    container_name: taiga-frontend-test
    # cap_add:
    #   - FOWNER
    # cap_drop:
    #   - ALL
    networks:
      - taiga
    ports:
      - 8000:8000
    depends_on:
      - taiga-frontend-test-events
      - taiga-frontend-test-backend
    environment:
      TZ: "Asia/Tokyo"
      FRONTEND_WORKER_PROC: "1"
      FRONTEND_WORKER_CONN: "1024"
      FRONTEND_API_URL: "http://localhost:8000/api/v1"
      FRONTEND_EVENTS_URL: "http://localhost:8000/events"
      BACKEND_LISTEN_SCHEME: "http"
      BACKEND_LISTEN_HOST: "taiga-frontend-test-backend"
      BACKEND_LISTEN_PORT: "8080"
      BACKEND_LISTEN_API_NAME: "api"
      BACKEND_LISTEN_ADMIN_NAME: "admin"
      EVENTS_LISTEN_SCHEME: "http"
      EVENTS_LISTEN_HOST: "taiga-frontend-test-events"
      EVENTS_LISTEN_PORT: "8888"
      EVENTS_LISTEN_NAME: "events"

  #
  # events
  #
  taiga-frontend-test-events:
    image: takumi/taiga-events:latest
    hostname: taiga-frontend-test-events
    container_name: taiga-frontend-test-events
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-frontend-test-rabbitmq
    environment:
      TZ: "Asia/Tokyo"
      EVENTS_SECRET: "taiga"
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga"
      RABBITMQ_HOST: "taiga-frontend-test-rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_NAME: "taiga"

  #
  # backend
  #
  taiga-frontend-test-backend:
    image: takumi/taiga-backend:latest
    hostname: taiga-frontend-test-backend
    container_name: taiga-frontend-test-backend
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-frontend-test-postgres
      - taiga-frontend-test-rabbitmq
      - taiga-frontend-test-redis
    environment:
      TZ: "Asia/Tokyo"
      BACKEND_DEBUG: "True"
      BACKEND_SECRET: "taiga"
      BACKEND_SCHEME: "http"
      BACKEND_HOSTNAME: "localhost"
      BACKEND_ADMIN_NAME: "Admin"
      BACKEND_ADMIN_EMAIL: "admin@example.com"
      BACKEND_CELERY_ENABLED: "True"
      BACKEND_GUNICORN_WORKER: "1"
      BACKEND_GUNICORN_TIMEOUT: "3"
      BACKEND_CELERY_CHILD: "1"
      BACKEND_CELERY_TIMELIMIT: "3"
      FRONTEND_SCHEME: "http"
      FRONTEND_HOSTNAME: "localhost"
      FRONTEND_MEDIA_URL: "http://localhost:8000/media/"
      FRONTEND_STATIC_URL: "http://localhost:8000/static/"
      POSTGRESQL_USER: "taiga"
      POSTGRESQL_PASS: "taiga"
      POSTGRESQL_HOST: "taiga-frontend-test-postgres"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_NAME: "taiga"
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga"
      RABBITMQ_HOST: "taiga-frontend-test-rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_NAME: "taiga"
      REDIS_HOST: "taiga-frontend-test-redis"
      REDIS_PORT: "6379"

  #
  # postgres
  #
  taiga-frontend-test-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-frontend-test-postgres
    container_name: taiga-frontend-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    tmpfs:
      - /var/lib/postgresql/data

  #
  # rabbitmq
  #
  taiga-frontend-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-frontend-test-rabbitmq
    container_name: taiga-frontend-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      TZ: "Asia/Tokyo"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    tmpfs:
      - /var/lib/rabbitmq/mnesia

  #
  # redis
  #
  taiga-frontend-test-redis:
    image: redis:alpine
    hostname: taiga-frontend-test-redis
    container_name: taiga-frontend-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      TZ: "Asia/Tokyo"

networks:
  taiga:
