version: '3.7'

services:
  #
  # build
  #
  taiga-frontend-build:
    build:
      context: .
      target: build
    image: takumi/taiga-frontend:build
    hostname: taiga-frontend-build
    container_name: taiga-frontend-build
    networks:
      - taiga

  #
  # service
  #
  taiga-frontend-test:
    build:
      context: .
      target: prod
    image: takumi/taiga-frontend:latest
    hostname: taiga-frontend-test
    container_name: taiga-frontend-test
    # cap_add:
    #   - FOWNER
    # cap_drop:
    #   - ALL
    networks:
      - taiga
    ports:
      - 8000:8000
    depends_on:
      - taiga-frontend-test-events
      - taiga-frontend-test-backend
    env_file:
      - ./test.env

  #
  # events
  #
  taiga-frontend-test-events:
    image: takumi/taiga-events:latest
    hostname: taiga-frontend-test-events
    container_name: taiga-frontend-test-events
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-frontend-test-rabbitmq
    env_file:
      - ./test.env

  #
  # backend
  #
  taiga-frontend-test-backend:
    image: takumi/taiga-backend:alpine
    hostname: taiga-frontend-test-backend
    container_name: taiga-frontend-test-backend
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-frontend-test-postgres
      - taiga-frontend-test-rabbitmq
      - taiga-frontend-test-redis
    env_file:
      - ./test.env

  #
  # postgres
  #
  taiga-frontend-test-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-frontend-test-postgres
    container_name: taiga-frontend-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    tmpfs:
      - /var/lib/postgresql/data

  #
  # rabbitmq
  #
  taiga-frontend-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-frontend-test-rabbitmq
    container_name: taiga-frontend-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    tmpfs:
      - /var/lib/rabbitmq/mnesia

  #
  # redis
  #
  taiga-frontend-test-redis:
    image: redis:alpine
    hostname: taiga-frontend-test-redis
    container_name: taiga-frontend-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
