version: '3'

services:
  #
  # taiga-front
  #
  taiga-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    image: takumi/taiga-front
    container_name: taiga-front
    restart: always
    environment:
      TAIGA_FRONTEND_EVENTS_BASE_URI: ${TAIGA_FRONTEND_EVENTS_BASE_URI}
      TAIGA_FRONTEND_BACKEND_BASE_URI: ${TAIGA_FRONTEND_BACKEND_BASE_URI}
    networks:
      - taiga
    ports:
      - ${TAIGA_FRONTEND_PORT}:80

  #
  # taiga-events
  #
  taiga-events:
    build:
      context: .
      dockerfile: Dockerfile.events
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: takumi/taiga-events
    container_name: taiga-events
    restart: always
    environment:
      TAIGA_EVENTS_SECRET: ${TAIGA_EVENTS_SECRET}
      TAIGA_EVENTS_RABBITMQ_HOST: taiga-events-rabbitmq
      TAIGA_EVENTS_RABBITMQ_PORT: 5672
      TAIGA_EVENTS_RABBITMQ_USER: taiga-events
      TAIGA_EVENTS_RABBITMQ_PASS: taiga-events
    networks:
      - taiga
    ports:
      - ${TAIGA_EVENTS_PORT}:8888
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:alpine
    container_name: taiga-events-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga-events
      RABBITMQ_DEFAULT_USER: taiga-events
      RABBITMQ_DEFAULT_PASS: taiga-events
    volumes:
      - taiga-events-rabbitmq:/var/lib/rabbitmq
    networks:
      - taiga

networks:
  taiga:

volumes:
  taiga-events-rabbitmq:
