version: '3.7'

services:
  #
  # frontend
  #
  taiga-frontend:
    image: takumi/taiga-frontend:latest
    hostname: taiga-frontend
    container_name: taiga-frontend
    restart: always
    # cap_add:
    #   - CHOWN
    #   - SETUID
    #   - SETGID
    #   - FOWNER
    # cap_drop:
    #   - ALL
    networks:
      - taiga
    ports:
      - 8000:8000
    depends_on:
      - taiga-events
      - taiga-backend
    secrets:
      - SITE_LISTEN_HOST
    env_file:
      - ./prod.env

  #
  # events
  #
  taiga-events:
    image: takumi/taiga-events:latest
    hostname: taiga-events
    container_name: taiga-events
    restart: always
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-rabbitmq
    secrets:
      - SITE_LISTEN_HOST
    env_file:
      - ./prod.env

  #
  # backend
  #
  taiga-backend:
    image: takumi/taiga-backend:alpine
    hostname: taiga-backend
    container_name: taiga-backend
    restart: always
    cap_drop:
      - ALL
    networks:
      - taiga
    depends_on:
      - taiga-postgres
      - taiga-rabbitmq
      - taiga-redis
    secrets:
      - SITE_LISTEN_HOST
    env_file:
      - ./prod.env
    volumes:
      - taiga-backend:/taiga-backend/media

  #
  # postgres
  #
  taiga-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-postgres
    container_name: taiga-postgres
    restart: always
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    env_file:
      - ./prod.env
    volumes:
      - taiga-postgres:/var/lib/postgresql/data

  #
  # rabbitmq
  #
  taiga-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-rabbitmq
    container_name: taiga-rabbitmq
    restart: always
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    env_file:
      - ./prod.env
    volumes:
      - taiga-rabbitmq:/var/lib/rabbitmq

  #
  # redis
  #
  taiga-redis:
    image: redis:alpine
    hostname: taiga-redis
    container_name: taiga-redis
    restart: always
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
volumes:
  taiga-backend:
  taiga-postgres:
  taiga-rabbitmq:
secrets:
  SITE_LISTEN_HOST:
    file: ./SITE_LISTEN_HOST.secret.env
