# vim: set ft=dockerfile :

FROM alpine

MAINTAINER Takumi Takahashi <takumiiinn@gmail.com>

ARG NO_PROXY
ARG FTP_PROXY
ARG HTTP_PROXY
ARG HTTPS_PROXY

COPY taiga-backend /taiga-backend
COPY taiga-backend-local.py /taiga-backend/settings/local.py

RUN echo Start! \
 && set -ex \
 && apk --update add --no-cache python3 python3-dev \
 && echo Complete!
