version: '3'

services:
  #
  # taiga-frontend
  #
  taiga-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: takumi/taiga-frontend
    container_name: taiga-frontend
    restart: always
    networks:
      - taiga
    ports:
      - ${TAIGA_FRONTEND_PORT}:80
    depends_on:
      - taiga-events
      - taiga-backend
    environment:
      TAIGA_FRONTEND_EVENTS_BASE_URI: "${TAIGA_FRONTEND_EVENTS_BASE_URI}"
      TAIGA_FRONTEND_BACKEND_BASE_URI: "${TAIGA_FRONTEND_BACKEND_BASE_URI}"

  #
  # taiga-events
  #
  taiga-events:
    build:
      context: .
      dockerfile: Dockerfile.events
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
    image: takumi/taiga-events
    container_name: taiga-events
    restart: always
    networks:
      - taiga
    ports:
      - ${TAIGA_EVENTS_PORT}:8888
    depends_on:
      - taiga-events-rabbitmq
    environment:
      TAIGA_EVENTS_SECRET: "${TAIGA_EVENTS_SECRET}"
      TAIGA_EVENTS_RABBITMQ_HOST: "taiga-events-rabbitmq"
      TAIGA_EVENTS_RABBITMQ_PORT: "5672"
      TAIGA_EVENTS_RABBITMQ_USER: "taiga-events"
      TAIGA_EVENTS_RABBITMQ_PASS: "taiga-events"

  taiga-events-rabbitmq:
    image: rabbitmq:alpine
    container_name: taiga-events-rabbitmq
    restart: always
    networks:
      - taiga
    volumes:
      - taiga-events-rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "taiga-events-rabbitmq"
      RABBITMQ_DEFAULT_USER: "taiga-events"
      RABBITMQ_DEFAULT_PASS: "taiga-events"

  #
  # taiga-backend
  #
  taiga-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        UBUNTU_MIRROR: ${UBUNTU_MIRROR}
    image: takumi/taiga-backend
    container_name: taiga-backend
    restart: always
    networks:
      - taiga
    ports:
      - ${TAIGA_BACKEND_PORT}:8000
    depends_on:
      - taiga-backend-postgres
    environment:
      TAIGA_BACKEND_DEBUG: "False"
      TAIGA_BACKEND_ADMIN_NAME: "Admin"
      TAIGA_BACKEND_ADMIN_EMAIL: "admin@example.com"
      TAIGA_BACKEND_POSTGRESQL_HOST: "taiga-backend-postgres"
      TAIGA_BACKEND_POSTGRESQL_PORT: "5432"
      TAIGA_BACKEND_POSTGRESQL_NAME: "taiga-backend"
      TAIGA_BACKEND_POSTGRESQL_USER: "taiga-backend"
      TAIGA_BACKEND_POSTGRESQL_PASS: "taiga-backend"
      TAIGA_BACKEND_API_SCHEME: "http"
      TAIGA_BACKEND_API_DOMAIN: "localhost"
      TAIGA_BACKEND_API_PORT: ""
      TAIGA_BACKEND_API_NAME: ""
      TAIGA_BACKEND_FRONT_SCHEME: ""
      TAIGA_BACKEND_FRONT_DOMAIN: ""
      TAIGA_BACKEND_FRONT_PORT: ""
      TAIGA_BACKEND_FRONT_NAME: ""
      TAIGA_BACKEND_MEDIA_URL: ""
      TAIGA_BACKEND_STATIC_URL: ""
      TAIGA_BACKEND_SECRET_KEY: ""

  taiga-backend-postgres:
    image: postgres:9.5-alpine
    container_name: taiga-backend-postgres
    restart: always
    networks:
      - taiga
    volumes:
      - taiga-backend-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "taiga-backend"
      POSTGRES_USER: "taiga-backend"
      POSTGRES_PASSWORD: "taiga-backend"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

networks:
  taiga:

volumes:
  taiga-events-rabbitmq:
  taiga-backend-postgres:
