version: '3'

services:
  taiga:
    build:
      context: .
      args:
        - NO_PROXY=${NO_PROXY}
        - FTP_PROXY=${FTP_PROXY}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - UBUNTU_MIRROR=${UBUNTU_MIRROR}
        - NODEJS_MIRROR=${NODEJS_MIRROR}
    image: takumi/taiga
    container_name: taiga
    networks:
      - taiga
    ports:
      - 8000:8000
      - 8888:8888
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:alpine
    container_name: taiga_postgres
    networks:
      - taiga
    volumes:
      - taiga-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga

  rabbitmq:
    image: rabbitmq:alpine
    container_name: taiga_rabbitmq
    networks:
      - taiga
    volumes:
      - taiga-rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga

networks:
  taiga:

volumes:
  taiga-postgres:
  taiga-rabbitmq:
