version: '3.7'

services:
  #
  # alpine build
  #
  taiga-backend-build-alpine:
    build:
      context: .
      dockerfile: alpine/Dockerfile
      target: build
    image: takumi/taiga-backend:build-alpine
    hostname: taiga-backend-build-alpine
    container_name: taiga-backend-build-alpine
    networks:
      - taiga

  #
  # xenial build
  #
  # taiga-backend-build-xenial:
  #   build:
  #     context: .
  #     dockerfile: xenial/Dockerfile
  #     target: build
  #   image: takumi/taiga-backend:build-xenial
  #   hostname: taiga-backend-build-xenial
  #   container_name: taiga-backend-build-xenial
  #   networks:
  #     - taiga

  #
  # alpine service
  #
  taiga-backend-xenial-test:
    build:
      context: .
      dockerfile: alpine/Dockerfile
      target: prod
    image: takumi/taiga-backend:alpine
    hostname: taiga-backend-alpine-test
    container_name: taiga-backend-alpine-test
    cap_drop:
      - ALL
    networks:
      - taiga
    ports:
      - 8000:8080
    depends_on:
      - taiga-backend-test-postgres
      - taiga-backend-test-rabbitmq
      - taiga-backend-test-redis
    env_file:
      - ./backend_test.env

  #
  # xenial service
  #
  # taiga-backend-xenial-test:
  #   build:
  #     context: .
  #     dockerfile: xenial/Dockerfile
  #     target: prod
  #   image: takumi/taiga-backend:latest
  #   hostname: taiga-backend-xenial-test
  #   container_name: taiga-backend-xenial-test
  #   cap_drop:
  #     - ALL
  #   networks:
  #     - taiga
  #   ports:
  #     - 8001:8080
  #   depends_on:
  #     - taiga-backend-test-postgres
  #     - taiga-backend-test-rabbitmq
  #     - taiga-backend-test-redis
  #   env_file:
  #     - ./backend_test.env

  #
  # postgres
  #
  taiga-backend-test-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-backend-test-postgres
    container_name: taiga-backend-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    tmpfs:
      - /var/lib/postgresql/data

  #
  # rabbitmq
  #
  taiga-backend-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-backend-test-rabbitmq
    container_name: taiga-backend-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    tmpfs:
      - /var/lib/rabbitmq/mnesia

  #
  # redis
  #
  taiga-backend-test-redis:
    image: redis:alpine
    hostname: taiga-backend-test-redis
    container_name: taiga-backend-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
