version: '3.7'

services:
  #
  # build
  #
  taiga-backend-build:
    build:
      context: .
      target: build
    image: takumi/taiga-backend:build
    hostname: taiga-backend-build
    container_name: taiga-backend-build
    networks:
      - taiga

  #
  # service
  #
  taiga-backend-test:
    build:
      context: .
      target: prod
    image: takumi/taiga-backend:latest
    hostname: taiga-backend-test
    container_name: taiga-backend-test
    cap_drop:
      - ALL
    networks:
      - taiga
    ports:
      - 8000:8080
    depends_on:
      - taiga-backend-test-postgres
      - taiga-backend-test-rabbitmq
      - taiga-backend-test-redis
    environment:
      # Django
      DJANGO_SECRET_KEY: "taiga"
      # PostgreSQL
      POSTGRESQL_USER: "taiga"
      POSTGRESQL_PASS: "taiga"
      POSTGRESQL_HOST: "taiga-backend-test-postgres"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_NAME: "taiga"
      # RabbitMQ
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga"
      RABBITMQ_HOST: "taiga-backend-test-rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_NAME: "taiga"
      # Redis
      REDIS_HOST: "taiga-backend-test-redis"
      REDIS_PORT: "6379"

  #
  # postgres
  #
  taiga-backend-test-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-backend-test-postgres
    container_name: taiga-backend-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    tmpfs:
      - /var/lib/postgresql/data

  #
  # rabbitmq
  #
  taiga-backend-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-backend-test-rabbitmq
    container_name: taiga-backend-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    tmpfs:
      - /var/lib/rabbitmq/mnesia

  #
  # redis
  #
  taiga-backend-test-redis:
    image: redis:alpine
    hostname: taiga-backend-test-redis
    container_name: taiga-backend-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
