version: '3'

services:
  #
  # taiga-backend
  #
  taiga-backend-test:
    build:
      context: .
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        UBUNTU_MIRROR: ${UBUNTU_MIRROR}
    image: takumi/taiga-backend
    container_name: taiga-backend-test
    networks:
      - taiga
    ports:
      - 8000:8000
    depends_on:
      - taiga-backend-test-postgres
    environment:
      BACKEND_DEBUG: "True"
      BACKEND_SECRET: "taiga"
      BACKEND_SCHEME: "http"
      BACKEND_HOSTNAME: "localhost"
      BACKEND_ADMIN_NAME: "Admin"
      BACKEND_ADMIN_EMAIL: "admin@example.com"
      BACKEND_CELERY_ENABLED: "True"
      BACKEND_GUNICORN_WORKER: "1"
      BACKEND_GUNICORN_TIMEOUT: "3"
      BACKEND_CELERY_CHILD: "1"
      BACKEND_CELERY_TIMELIMIT: "3"
      FRONTEND_SCHEME: "http"
      FRONTEND_HOSTNAME: "localhost"
      FRONTEND_MEDIA_URL: "http://localhost/media/"
      FRONTEND_STATIC_URL: "http://localhost/static/"
      POSTGRESQL_HOST: "taiga-backend-test-postgres"
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_NAME: "taiga"
      POSTGRESQL_USER: "taiga"
      POSTGRESQL_PASS: "taiga"
      RABBITMQ_PEER_USER: "taiga"
      RABBITMQ_PEER_PASS: "taiga"
      RABBITMQ_PEER_HOST: "taiga-backend-test-rabbitmq"
      RABBITMQ_PEER_PORT: "4369"
      RABBITMQ_PEER_PATH: "taiga"
      RABBITMQ_NODE_USER: "taiga"
      RABBITMQ_NODE_PASS: "taiga"
      RABBITMQ_NODE_HOST: "taiga-backend-test-rabbitmq"
      RABBITMQ_NODE_PORT: "5672"
      RABBITMQ_NODE_PATH: "taiga"
      REDIS_HOST: "taiga-backend-test-redis"
      REDIS_PORT: "6379"

  taiga-backend-test-postgres:
    image: postgres:9.5-alpine
    container_name: taiga-backend-test-postgres
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

  taiga-backend-test-rabbitmq:
    image: rabbitmq:alpine
    container_name: taiga-backend-test-rabbitmq
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_VHOST: "taiga-backend-test-rabbitmq"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"

  taiga-backend-test-redis:
    image: redis:alpine
    container_name: taiga-backend-test-redis
    networks:
      - taiga

networks:
  taiga:
