version: '3.7'

services:
  #
  # alpine build
  #
  # taiga-build-backend-alpine:
  #   build:
  #     context: .
  #     dockerfile: alpine/Dockerfile
  #     target: build
  #   image: takumi/taiga-backend:build-alpine
  #   hostname: taiga-build-backend-alpine
  #   container_name: taiga-build-backend-alpine
  #   networks:
  #     - taiga

  #
  # xenial build
  #
  taiga-build-backend-xenial:
    build:
      context: .
      dockerfile: xenial/Dockerfile
      target: build
    image: takumi/taiga-backend:build-xenial
    hostname: taiga-build-backend-xenial
    container_name: taiga-build-backend-xenial
    networks:
      - taiga

  #
  # alpine service
  #
  # taiga-test-backend-alpine:
  #   build:
  #     context: .
  #     dockerfile: alpine/Dockerfile
  #     target: prod
  #   image: takumi/taiga-backend:alpine
  #   hostname: taiga-test-backend-alpine
  #   container_name: taiga-test-backend-alpine
  #   cap_drop:
  #     - ALL
  #   networks:
  #     - taiga
  #   ports:
  #     - 8000:8080
  #   depends_on:
  #     - taiga-test-postgres
  #     - taiga-test-rabbitmq
  #     - taiga-test-redis
  #   env_file:
  #     - ./test.env

  #
  # xenial service
  #
  taiga-test-backend-xenial:
    build:
      context: .
      dockerfile: xenial/Dockerfile
      target: prod
    image: takumi/taiga-backend:latest
    hostname: taiga-test-backend-xenial
    container_name: taiga-test-backend-xenial
    cap_drop:
      - ALL
    networks:
      - taiga
    ports:
      - 8000:8080
    depends_on:
      - taiga-test-postgres
      - taiga-test-rabbitmq
      - taiga-test-redis
    env_file:
      - ./test.env

  #
  # postgres
  #
  taiga-test-postgres:
    image: postgres:9.5-alpine
    hostname: taiga-test-postgres
    container_name: taiga-test-postgres
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

  #
  # rabbitmq
  #
  taiga-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-test-rabbitmq
    container_name: taiga-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"

  #
  # redis
  #
  taiga-test-redis:
    image: redis:alpine
    hostname: taiga-test-redis
    container_name: taiga-test-redis
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga

networks:
  taiga:
