version: '3'

services:
  #
  # taiga-backend
  #
  taiga-backend-test:
    build:
      context: .
      args:
        NO_PROXY: ${NO_PROXY}
        FTP_PROXY: ${FTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        UBUNTU_MIRROR: ${UBUNTU_MIRROR}
    image: takumi/taiga-backend
    container_name: taiga-backend-test
    networks:
      - taiga
    ports:
      - ${TAIGA_BACKEND_TEST_FRONT_PORT}:8000
      - ${TAIGA_BACKEND_TEST_API_PORT}:9000
    depends_on:
      - taiga-backend-test-postgres
    environment:
      TAIGA_BACKEND_DEBUG: "True"
      TAIGA_BACKEND_ADMIN_NAME: "Admin"
      TAIGA_BACKEND_ADMIN_EMAIL: "admin@example.com"
      TAIGA_BACKEND_SECRET_KEY: "taiga"
      TAIGA_BACKEND_POSTGRESQL_HOST: "taiga-backend-test-postgres"
      TAIGA_BACKEND_POSTGRESQL_PORT: "5432"
      TAIGA_BACKEND_POSTGRESQL_NAME: "taiga"
      TAIGA_BACKEND_POSTGRESQL_USER: "taiga"
      TAIGA_BACKEND_POSTGRESQL_PASS: "taiga"
      TAIGA_BACKEND_RABBITMQ_USER: "taiga"
      TAIGA_BACKEND_RABBITMQ_PASS: "taiga"
      TAIGA_BACKEND_RABBITMQ_HOST: "taiga-backend-test-rabbitmq"
      TAIGA_BACKEND_RABBITMQ_PORT: "4369"
      TAIGA_BACKEND_RABBITMQ_PATH: ""
      TAIGA_BACKEND_SITES_API_SCHEME: "http"
      TAIGA_BACKEND_SITES_API_DOMAIN: ${TAIGA_BACKEND_TEST_HOST}
      TAIGA_BACKEND_SITES_API_PORT: ${TAIGA_BACKEND_TEST_API_PORT}
      TAIGA_BACKEND_SITES_FRONT_SCHEME: "http"
      TAIGA_BACKEND_SITES_FRONT_DOMAIN: ${TAIGA_BACKEND_TEST_HOST}
      TAIGA_BACKEND_SITES_FRONT_PORT: ${TAIGA_BACKEND_TEST_API_PORT}
      TAIGA_BACKEND_MEDIA_URL: "http://${TAIGA_BACKEND_TEST_HOST}/media/"
      TAIGA_BACKEND_STATIC_URL: "http://${TAIGA_BACKEND_TEST_HOST}/static/"

  taiga-backend-test-postgres:
    image: postgres:9.5-alpine
    container_name: taiga-backend-test-postgres
    networks:
      - taiga
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "taiga"
      POSTGRES_PASSWORD: "taiga"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"

  taiga-backend-test-rabbitmq:
    image: rabbitmq:alpine
    container_name: taiga-backend-test-rabbitmq
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_VHOST: "taiga-backend-test-rabbitmq"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"

networks:
  taiga:
