# -*- coding: utf-8 -*-

from .common import *

# SECRET = 'TAIGA_BACKEND_SECRET'

# DATABASES['default']['HOST'] = 'TAIGA_POSTGRESQL_HOST'
# DATABASES['default']['PORT'] = 'TAIGA_POSTGRESQL_PORT'
# DATABASES['default']['NAME'] = 'TAIGA_POSTGRESQL_NAME'
# DATABASES['default']['USER'] = 'TAIGA_POSTGRESQL_USER'
# DATABASES['default']['PASSWORD'] = 'TAIGA_POSTGRESQL_PASS'

# EVENTS_PUSH_BACKEND = 'taiga.events.backends.rabbitmq.EventsPushBackend'
# EVENTS_PUSH_BACKEND_OPTIONS = {'url': 'ampq//TAIGA_RABBITMQ_USER:TAIGA_RABBITMQ_PASS@TAIGA_RABBITMQ_HOST:TAIGA_RABBITMQ_PORT/TAIGA_RABBITMQ_PATH'}

# SITES['api']['scheme'] = 'TAIGA_BACKEND_SCHEME'
# SITES['api']['domain'] = 'TAIGA_BACKEND_DOMAIN:TAIGA_BACKEND_PORT'

# MEDIA_URL = 'TAIGA_BACKEND_MEDIA_URL'
# STATIC_URL = 'TAIGA_BACKEND_STATIC_URL'
