# -*- coding: utf-8 -*-

from .common import *

# SECRET_KEY = 'TAIGA_BACKEND_SECRET_KEY'

# DATABASES['default']['HOST'] = 'TAIGA_BACKEND_POSTGRESQL_HOST'
# DATABASES['default']['PORT'] = 'TAIGA_BACKEND_POSTGRESQL_PORT'
# DATABASES['default']['NAME'] = 'TAIGA_BACKEND_POSTGRESQL_NAME'
# DATABASES['default']['USER'] = 'TAIGA_BACKEND_POSTGRESQL_USER'
# DATABASES['default']['PASSWORD'] = 'TAIGA_BACKEND_POSTGRESQL_PASS'

# EVENTS_PUSH_BACKEND = 'taiga.events.backends.rabbitmq.EventsPushBackend'
# EVENTS_PUSH_BACKEND_OPTIONS['url'] = 'ampq//TAIGA_BACKEND_RABBITMQ_USER:TAIGA_BACKEND_RABBITMQ_PASS@TAIGA_BACKEND_RABBITMQ_HOST:TAIGA_BACKEND_RABBITMQ_PORT/TAIGA_BACKEND_RABBITMQ_PATH'

# SITES['api']['scheme'] = 'TAIGA_BACKEND_SITES_API_SCHEME'
# SITES['api']['domain'] = 'TAIGA_BACKEND_SITES_API_DOMAIN:TAIGA_BACKEND_SITES_API_PORT'
# SITES['front']['scheme'] = 'TAIGA_BACKEND_SITES_FRONT_SCHEME'
# SITES['front']['domain'] = 'TAIGA_BACKEND_SITES_FRONT_DOMAIN:TAIGA_BACKEND_SITES_FRONT_PORT'

# MEDIA_URL = 'TAIGA_BACKEND_MEDIA_URL'
# STATIC_URL = 'TAIGA_BACKEND_STATIC_URL'
