version: '3.7'

services:
  #
  # build
  #
  taiga-events-build:
    build:
      context: .
      target: build
    image: takumi/taiga-events:build
    hostname: taiga-events-build
    container_name: taiga-events-build
    networks:
      - taiga

  #
  # service
  #
  taiga-events-test:
    build:
      context: .
      target: prod
    image: takumi/taiga-events:latest
    hostname: taiga-events-test
    container_name: taiga-events-test
    cap_drop:
      - ALL
    networks:
      - taiga
    ports:
      - 8888:8888
    depends_on:
      - taiga-events-test-rabbitmq
    environment:
      TZ: "Asia/Tokyo"
      EVENTS_SECRET: "taiga"
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga"
      RABBITMQ_HOST: "taiga-events-test-rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_NAME: "taiga"

  #
  # rabbitmq
  #
  taiga-events-test-rabbitmq:
    image: rabbitmq:alpine
    hostname: taiga-events-test-rabbitmq
    container_name: taiga-events-test-rabbitmq
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    networks:
      - taiga
    environment:
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    tmpfs:
      - /var/lib/rabbitmq/mnesia

networks:
  taiga:
